# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMPipeline-conn'
    subscriptionId: '964c10bb-8a6c-43bc-83d3-6b318c6c7305'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'shumintest01'
    location: 'central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/xsm52lyf/ARMPipeline-repo/main/create_web_app/azuredeploy.json'
    overrideParameters: '-projectName smtest'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
